### ISSUE TITLE
--trunclen only applies to song

### ISSUE THREAD

**Issue by sgraf812** [Jvanrhijn/polybar-spotify#17]
It's not really truncating the whole message, just the song.

Reading the description in the README, this sounds like a feature, but just wanted to make sure.

**Comment by Jvanrhijn** [comment]
It should truncate the entire thing now. Maybe it's best to increase default value for `trunclen`, 20 chars total is a bit short for artist + song. Thoughts?

**Comment by sgraf812** [comment]
Thanks! No particular preference here. I'd truncate it to 20, but that might not work for everybody. I expect people to tweak this setting to their liking anyway.

**Comment by Jvanrhijn** [comment]
I'll just increase it by 10, as apparently [the median artist name length](https://musicmachinery.com/2012/01/07/have-artist-names-been-getting-longer/) is 11 characters :) 

Since I don't really use the script anymore nowadays I can't really judge whether 20 is too short, but with `trunclen = 35` most people probably won't notice the change.
